name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: DGT-Human
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake-dark.svg
            
      - name: Pull latest changes
        run: git pull origin main --rebase
        
      - name: Push the SVG files to the output branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate GitHub contribution grid snake animation"
          add: "output/*.svg"
